spring.application.name=RevPlay_P2

server.port=9090

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=revplay
spring.datasource.password=revplay
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

logging.file.name=spring.log
